name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore PrivacyEnforcerPro.sln

      - name: Build
        run: dotnet build PrivacyEnforcerPro.sln -c Release --no-restore

      - name: Publish UI (win-x64)
        run: dotnet publish PrivacyEnforcerPro/PrivacyEnforcerPro.UI/PrivacyEnforcerPro.UI.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true --no-build

      - name: Package artifact
        shell: pwsh
        run: |
          $publish = Get-ChildItem -Recurse -Directory "PrivacyEnforcerPro/PrivacyEnforcerPro.UI/bin/Release" | Where-Object { $_.FullName -like "*win-x64\\publish" } | Select-Object -First 1
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          $zipPath = "artifacts/$env:GITHUB_REF_NAME-PrivacyEnforcerPro-UI-win-x64.zip"
          Compress-Archive -Path "$($publish.FullName)/*" -DestinationPath $zipPath -Force
          "$([string]::Format('ZIP_PATH={0}', $zipPath))" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_PATH }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}